logging:
    level:
        org:
            springframework:
                boot: INFO
                webflow: INFO
spring:
    thymeleaf:
        cache: false
    resources:
        cache-period: 0